# Generated by Django 2.1.5 on 2019-03-12 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_feeding'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeding',
            name='kid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main_app.Kid'),
            preserve_default=False,
        ),
    ]
