# Generated by Django 2.1.5 on 2019-03-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190313_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='toys',
            field=models.ManyToManyField(to='main_app.Toy'),
        ),
    ]
